### ISSUE TITLE
execve() (EACCES (Permission denied)) for /usr/bin/env

### ISSUE THREAD

**Issue by playbyan1453** [ZhymabekRoman/Exagear-For-Termux#10]
Hi, I have some Linux wine 3.0 obb that I use on exagear apk. I tried runing it on termux and I extract the obb file to a folder and rename it to "exagear-fs" the I moved it to termux exagear directory, run the script with the error message like this
`lkv_LoadApp: execve() is guaranteed to fail with -13 (EACCES (Permission denied)) for /usr/bin/env`
also I'm very new to Linux so how to fix it?

[Obb Download](https://www.mediafire.com/file/rg6kkwvo5ykfu0h/ED_OpenGL_Mesa3D_17.3.9.zip/file)
Inside the archive it have the obb itself.

**Comment by ZhymabekRoman** [comment]
I do not know why it does not want to work for you, but everything works fine for me. My actions:
0) Clone Exagear-For-Termux
1) Init submodule proot-static
2) Download you obb file: https://www.mediafire.com/file/rg6kkwvo5ykfu0h/ED_OpenGL_Mesa3D_17.3.9.zip/file
3) Extract:
```
cd Exagear-For-Termux
unzip ED_OpenGL_Mesa3D_17.3.9.zip
unzip com.eltechs.ed/main.30.com.eltechs.ed.obb -d exagear-fs/
```
Screenshot:

**Comment by ZhymabekRoman** [comment]
I am closing the issue, due to insufficient information

**Comment by playbyan1453** [comment]
Sorry for late reply my internet having a problem lately, thanks for the guide probably i use third party unzipper like zarchiver so it couldn't have the things like folder attributes so it have those execve error.

**Comment by Saikatsaha1996** [comment]
> I do not know why it does not want to work for you, but everything works fine for me. My actions: 0) Clone Exagear-For-Termux
> 
> 1. Init submodule proot-static
> 2. Download your obb file: https://www.mediafire.com/file/rg6kkwvo5ykfu0h/ED_OpenGL_Mesa3D_17.3.9.zip/file
> 3. Extract:
> 
> ```
> cd Exagear-For-Termux
> unzip ED_OpenGL_Mesa3D_17.3.9.zip
> unzip com.eltechs.ed/main.30.com.eltechs.ed.obb -d exagear-fs/
> ```
> 
> Screenshot: ![Screenshot_20210924_101950](https://user-images.githubusercontent.com/61125068/134617715-f08979c2-3919-45e3-b408-ff7d00bf36b8.jpg)

Can you guide me actually i am trying to build my own obb..

How can I build with.. can you help?

**Comment by playbyan1453** [comment]
![Screenshot_2022-07-28-22-16-42-835_com termux](https://user-images.githubusercontent.com/62523229/181574803-c47c7751-d582-4a24-88c3-435db3a0e678.jpg)
Thank you so much It worked, so it is possible to zip it to obb right?

**Comment by ZhymabekRoman** [comment]
>  so it is possible to zip it to obb right?
Yep

**Comment by playbyan1453** [comment]
Tried to zip the obb, but the file is over 1 gb. Is there any way to fix it?
