### ISSUE TITLE
Медленное чтение/запись внутри контейнера

### ISSUE THREAD

**Issue by Fragrus** [ZhymabekRoman/Exagear-For-Termux#11]
Использовал сначала предложенный в README debian, позже из этого же репо выкачал посвежее - результат один, в самом контейнере очень медленная скорость чтения и записи, прямо совсем ужасно. 
До этого ставил ExaGear с wine (версия если не ошибаюсь 3.0.1) - дак там в мгновение ока всё происходило. 
Для сравнения, я запускал сервер HLDS Counter Strike 1.6 в wine - там 3 секунды и карта уже загрузилась.
Здесь же внутри debian я жду по минут 5 наверное.
Что можно с этим сделать?

**Comment by ZhymabekRoman** [comment]
> очень медленная скорость чтения и записи, прямо совсем ужасно.

согласен, но с этим я ничего не могу поделать, это из-за того что используется proot:
```
PRoot is slow.

Every process is hooked through ptrace(), so PRoot can hijack the system call arguments and return values. This is typically used to translate file paths so traced program will see the different file system layout.
```


> До этого ставил ExaGear с wine (версия если не ошибаюсь 3.0.1)

А как конкретно ставили? Также в proot Exagear Desktop ставили?

**Comment by ZhymabekRoman** [comment]
> root приложение не просило, из этого могу сделать вывод, что было в proot

ну как бы .... грубо говоря да там также используется ptrace как и в proot чтобы перехватывать системные вызовы

> Видимо надо всё же пробовать chroot

Запускать в Chroot ИМХО не совсем хорошая идея, т.к. все таки proot больше эмулирует не достающиеся вызовы Андройда
