### ISSUE TITLE
 upgrading or install apps give  an error

### ISSUE THREAD

**Issue by anwarmax-cpu** [ZhymabekRoman/Exagear-For-Termux#13]
When i upgrade or install apps like xorg  it will endup with  an error
![20211105_004158_rmscr](https://user-images.githubusercontent.com/77493923/140430405-83e2bc38-8947-4e7c-8d7e-5fd33a333752.jpg)

**Comment by ZhymabekRoman** [comment]
`rm /var/lib/dpkg/info/systemd.postinst`

**Comment by anwarmax-cpu** [comment]
Thanks  for the fast replay it works

**Comment by anwarmax-cpu** [comment]
Thanks  for the fast replay it works
