### ISSUE TITLE
how to acces external(host) sorage

### ISSUE THREAD

**Issue by anwardad** [ZhymabekRoman/Exagear-For-Termux#14]
i was not able to create symbolic link to "/host-roots/sdcard"  or  "/host-roots/otg device address" how could i do that from within the container

**Comment by ZhymabekRoman** [comment]
Host internal memory: `cd /storage/emulated/0/`
Host external memory (SD card): `cd /storage/*-*` (on some devices this command may not works)

**Comment by anwardad** [comment]
no such file or directory
![20220310_171314_rmscr](https://user-images.githubusercontent.com/43036847/157682750-ae7e2609-d95f-42df-96b1-3360fb8aaab3.jpg)

**Comment by anwardad** [comment]
i have managed to fix the problem by using user land asset x86-rootfs.tar.gz file its 900mb after installation but it had the  /host-roots/sdcard link build in.

but on other topic i know this is not the scope of this project but is it possible to disable the x86 to arm translator to just run arm distros in a container (i planed to run raspberry pi OS) i know there is method on termux but on user land you only work on what they give you (alpin,Kali,Debian,Ubuntu and all run separately )  you could close this  Issue

**Comment by ZhymabekRoman** [comment]
> to disable the x86 to arm translator to just run arm distros in a container

If you have root use chroot or maybe Docker, if not use proot.
