### ISSUE TITLE
problem with dpkg 

### ISSUE THREAD

**Issue by erfty125** [ZhymabekRoman/Exagear-For-Termux#18]
root@localhost:/# apt upgrade                     Reading package lists... Done                     Building dependency tree... Done                  Reading state information... Done                 Calculating upgrade... Done                       The following NEW packages will be installed:       exfatprogs                                      The following packages will be upgraded:            bash bsdutils dbus dbus-user-session dpkg         fdisk gpgv gzip libblkid1 libbluray2 libc-bin     libc6 libcryptsetup12 libdbus-1-3 libexpat1       libfdisk1 libfreetype6 libgmp10 libgnutls30       libgssapi-krb5-2 libk5crypto3 libkrb5-3           libkrb5support0 liblzma5 libmount1                libpam-modules libpam-modules-bin                 libpam-runtime libpam-systemd libpam0g            libpcre2-8-0 libpolkit-agent-1-0                  libpolkit-gobject-1-0 libseccomp2                 libsmartcols1 libssl1.1 libsystemd0               libtirpc-common libtirpc3 libudev1                libudisks2-0 libuuid1 libxml2 mount openssl       perl-base systemd systemd-sysv                    systemd-timesyncd sysvinit-utils tzdata udev      udisks2 util-linux zlib1g                       55 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.                                     Need to get 0 B/29.8 MB of archives.              After this operation, 383 kB of additional disk space will be used.                                 Do you want to continue? [Y/n] y                  debconf: delaying package configuration, since apt-utils is not installed                           E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)           (Reading database ... 9023 files and directories currently installed.)
Preparing to unpack .../bash_5.1-2+deb11u1_i386.deb ...
clone: FATAL: attempted to create non-posix thread; clone_flags == 00004111
dpkg: error processing archive /var/cache/apt/archives/bash_5.1-2+deb11u1_i386.deb (--unpack):
 new bash package pre-installation script subprocess returned error exit status 1
update-alternatives: using /usr/share/man/man7/bash-builtins.7.gz to provide /usr/share/man/man7/builtins.7.gz (builtins.7.gz) in auto mode
Errors were encountered while processing:
 /var/cache/apt/archives/bash_5.1-2+deb11u1_i386.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@localhost:/#

**Comment by ZhymabekRoman** [comment]
Thanks for using Exagear For Termux. This problem is already known to us, there is no solution yet. See: https://github.com/ZhymabekRoman/Exagear-For-Termux/issues/16

**Comment by erfty125** [comment]
also this is my problem , or exatermux? i just want to upgrade and apktool is not working becouse of this.

**Comment by ZhymabekRoman** [comment]
@erfty125, problem in Exagear

**Comment by ZhymabekRoman** [comment]
Не знаю честно, смогу ли я это исправить

**Comment by ZhymabekRoman** [comment]
Скорее всего это баг в самом движке транслятора Exagear
