### ISSUE TITLE
Добавить proot-static

### ISSUE THREAD

**Issue by ezhik123** [ZhymabekRoman/Exagear-For-Termux#2]
Вы видимо забыли добавить proot_static.. Подскажите пожалуйста как его установить в ваш ExaGearForTermux?

**Comment by ZhymabekRoman** [comment]
@ezhik123 Здравствуйте, спасибо что написали, да действительно я забыл добавить в инструкцию команды для инициализации модуля proot-static. Инструкцию я починил, теперь все хорошо должно быть. Вот команды для инициализации модуля proot-static:
cd ~/ExaTermux
git submodule init
git submodule update
