### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mesflit** [ZhymabekRoman/Exagear-For-Termux#20]
How to start and connect to vnc or wayland.
Need to install something like Xfce4?
And how do I start the exe programs I downloaded?

**Comment by ZhymabekRoman** [comment]
> How to start and connect to vnc or wayland.

```
apt install tightvncserver -y
vncserver
```

> Need to install something like Xfce4?

If you want full Desktop environment you should install Xfce4. Or else you can just use a windows manager like openbox.


> And how do I start the exe programs I downloaded?

Install Wine and execute exe file using it: wine example.exe
