### ISSUE TITLE
Cant find bin?

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [ZhymabekRoman/Exagear-For-Termux#24]
Ok so when i type ./start-exagear login it gives me this error.

~/ExaTermux $ ./start-exagear.sh login            
    ░█░█░█▀█░█▀▄░█▀█                                  ░░▀█░█▀▀░█░█░█▀█
    ░░░▀░▀░░░▀▀░░▀░▀                              
ExaGear for Termux by Zhymabek_Roman              Version: 3.1-stable, 2021-2023                                                                      Copyright (c) 2013-2019 'Elbrus Technologies' LLC. All rights reserved.                             This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                                                                       System memory configuration is determined as 3g   Folder 'bin' in guest system not found. The guest system is likely damaged. Exit...                 

But when i type ls.

~/ExaTermux $ ls                                  LICENSE    debian-i686-pd-v2.2.0.tar.xz           README.md  exagear-fs                             bin        start-exagear.sh                       

Or mkdir

~/ExaTermux $ mkdir bin                           mkdir: cannot create directory ‘bin’: File exists 
~/ExaTermux $

It says the bin file exists but the sh script cant find it, ill nano the script and check whats happening too.

**Comment by GuythatUhmCreatesRandomStuff** [comment]
![Screenshot_20240110-201452_Termux](https://github.com/ZhymabekRoman/Exagear-For-Termux/assets/144390627/ae4472f1-871f-42a0-829b-0e8bc11a021d)
I have accidentally closed the issue, also i am using the updated rootfs for proot-distro since the old ones were gone.

**Comment by GuythatUhmCreatesRandomStuff** [comment]
the contents of the Debian-i686 folder
![Uploading Screenshot_20240110-202342_Termux.jpg…]()

**Comment by GuythatUhmCreatesRandomStuff** [comment]
![Screenshot_20240110-202342_Termux](https://github.com/ZhymabekRoman/Exagear-For-Termux/assets/144390627/85993c45-2ac7-4511-9eef-f4a05dedb72b)

**Comment by ZhymabekRoman** [comment]
I will update README file

**Comment by ZhymabekRoman** [comment]
Please remove existing folder, and repeat all steps from README file:
```
rm -rfv ~/ExaTermux
```

**Comment by ZhymabekRoman** [comment]
```
ls ./
ls exagear-fs/
```

**Comment by GuythatUhmCreatesRandomStuff** [comment]
> ```
> ls ./
> ls exagear-fs/
> ```

![Screenshot_20240112-161901_Termux](https://github.com/ZhymabekRoman/Exagear-For-Termux/assets/144390627/71c5960d-48e2-4503-821a-f46bff634ca7)

**Comment by ZhymabekRoman** [comment]
Second command:
ls exagear-fs/

**Comment by GuythatUhmCreatesRandomStuff** [comment]
![Screenshot_20240113-070655_Termux](https://github.com/ZhymabekRoman/Exagear-For-Termux/assets/144390627/192b0fd9-97fa-47af-9b3a-13c9e062a922)

**Comment by GuythatUhmCreatesRandomStuff** [comment]
> Second command: ls exagear-fs/

^

**Comment by ZhymabekRoman** [comment]
Do:
cd ~/ExaTermux
mv exagear-fs/debian-i686 exagear-fs

**Comment by GuythatUhmCreatesRandomStuff** [comment]
![Screenshot_20240113-105146_Termux](https://github.com/ZhymabekRoman/Exagear-For-Termux/assets/144390627/9ef0ce38-a520-4ddf-adc1-0e07c139db5f)


> Do: cd ~/ExaTermux mv exagear-fs/debian-i686/* exagear-fs/

**Comment by ZhymabekRoman** [comment]
do EXACTLY how written:
`mv exagear-fs/debian-i686/* exagear-fs/`

YOU executed command without `/*`. 

AGAIN: `mv exagear-fs/debian-i686/* exagear-fs/`

**Comment by GuythatUhmCreatesRandomStuff** [comment]
> do EXACTLY how written: `mv exagear-fs/debian-i686/* exagear-fs/`
> 
> YOU executed command without `/*`.
> 
> AGAIN: `mv exagear-fs/debian-i686/* exagear-fs/`

It worked, thanks for help
