### ISSUE TITLE
files and folders not found

### ISSUE THREAD

**Issue by devicewhite** [ZhymabekRoman/Exagear-For-Termux#25]
I have already detected the reason for this failure, normally it was to rename the "debian-i686" folder to "exagear-fs"... but the folder already exists, so it ends up being moved to inside it

as a result we get a directory "exagear-fs/debian-i686/<all other files>"

my recommendation: remove "mkdir exagear-fs" from the commands

![Screenshot_2024-02-06-23-09-31-690_com termux](https://github.com/ZhymabekRoman/Exagear-For-Termux/assets/65994174/14afd943-ccdc-4246-88cd-654c01e7c6a6) #

**Comment by ZhymabekRoman** [comment]
Thanks, fixed!
