### ISSUE TITLE
Alpine linux gives this error

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [ZhymabekRoman/Exagear-For-Termux#26]
Here is the error it gives me:
~/ExaTermux $ ./start-exagear.sh login

    ░█░█░█▀█░█▀▄░█▀█
    ░░▀█░█▀▀░█░█░█▀█
    ░░░▀░▀░░░▀▀░░▀░▀

ExaGear for Termux by Zhymabek_Roman
Version: 3.1-stable, 2021-2023

Copyright (c) 2013-2019 'Elbrus Technologies' LLC. All rights reserved.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

System memory configuration is determined as 3g
Writing resolv.conf file (NS 8.8.8.8/8.8.4.4)...
Folder 'storage' in guest system not found. Creating....

Folder 'dev' in guest system not found. Creating....                                                        Your environment is defined as Termux

[Starting x86 environment]

Attempt to delete pinned vma 0x0xab62b3e8 [0x800c9000, 0x800ca000)
[Exit from x86 environment with error status]
~/ExaTermux $
I use the rootfs 4.6.0 alpine from proot-distro's latest alpine. With exclude dev*

**Comment by ZhymabekRoman** [comment]
Due to memory security mechanisms, Alpine does not work with Exagear.
