### ISSUE TITLE
wine win32k error

### ISSUE THREAD

**Issue by fengxue-jrql** [ZhymabekRoman/Exagear-For-Termux#3]
the wine service win32k is not work,in some time,wine couldn't find bass.dll,even though the bass.dll is exit。

**Comment by ZhymabekRoman** [comment]
@fengxue-jrql Hello, what version of Wine are you using? Which command did you install Wine? And specifically in which program does this happen?

**Comment by fengxue-jrql** [comment]
I install the wine with the winehq wiki teach ,and add the ppa sdl2,wine version is wine-staging-6.7,
wine I start the wine ,the terminal tell me the win32.sys load error,but the wine start success。when i start a chinese game pvz,the wine tell me couldn't find bass.dll,even though the bass.dll exit in the games file. 
       tanks you creat the shell script ,now I crete a deb for termux, use rootfs ubuntu18.04 ,you can get it https://pan.baidu.com/s/1tZY1Wiwn3_tLglwCBbzteQ 提取码:ficq ,how to use:https://b23.tv/tvVKCs。
       today I build a obb for ed302 ,the obb and apk is free for all person .you coud find it at https://b23.tv/X2QnuS

**Comment by ZhymabekRoman** [comment]
> wine tell me couldn't find bass.dll,even though the bass.dll exit in the games file.

It seems to me that this is a problem in Wine itself, Exagear For Termux has nothing to do with this. Try the steps described here: https://answers.microsoft.com/en-us/windows/forum/windows_other-gaming/bassdll-not-found/5a65c7f6-fbf6-46e2-8cad-94595fd76c2c#_self

> today I build a obb for ed302 ,the obb and apk is free for all person

Thank you very much, someday I will try

> tanks you creat the shell script ,now I crete a deb for termux, use rootfs ubuntu18.04

I thought about it, within a month I will try build Exagear For Termux with Ubuntu 18, Ubuntu 20 and pack in deb package, thank you

> the terminal tell me the win32.sys load error,

Hmm, this is interesting, most likely it is related to Linux kernel of Android, someday I will look
