### ISSUE TITLE
Can't open any type of terminal emulators in desktop environment vncserver

### ISSUE THREAD

**Issue by Rj1178** [ZhymabekRoman/Exagear-For-Termux#4]
Hello sir, I have this weird issue i could open any type of terminal emulator when I tried in vncserver , I tried using ubuntu and debain image , but in ubuntu no termuinal opens and in debian image (you linked) gives that failed to start child error , no pty , i tried using xterm , xterm doesn't open or responds and uxterm gives that error uxterm tried to use en_US.utf8 locale by setting LC_All , I could bypass that issue if I edit that sh script LC_All=C or LC_All= or deleting Lc_all command completely or after that uxterm like same doesn't respond or opens 

Please note that I am just an average person no knowledge ,at all, it maybe my fault and I have been trying following a lot of ubuntu website and 
Some youtube videos but i ask them they don't reply , and i have been trying it for weeks to get to work , coz i can't do anything without terminal in desktop environment vnc , 

I couldn't find any other guide or information about ExaTermux I know it may be my fault being so noob , but i have been trying for weeks to understand and try Exatermux, and i don't want to give up, i want to run 32bit apps windows through exatermux

I know sir, You are a busy person ,I didn't know any other way to contact you coz I just texted here , if there is any way to contact, 

Please considering helping me sensei plzzzz,

**Comment by ZhymabekRoman** [comment]
Hello, I apologize that I did not answer, I was very busy. Thank you so much for the bug report, I will definitely see what is wrong there.

**Comment by ZhymabekRoman** [comment]
I will have to close this issue as it is a duplicate #5
