### ISSUE TITLE
Failed to open PTY in xfce4 tigervnc desktop

### ISSUE THREAD

**Issue by fengxue-jrql** [ZhymabekRoman/Exagear-For-Termux#5]
I can't run xfce4-terminal in xfce4 desktop,but I can run xfce4 terminal on TermuxExager version 2.0.but the version 2.1 speed is higer tan 2.0.
![Screenshot_2021-05-13-19-01-24-413_com realvnc viewer android](https://user-images.githubusercontent.com/57759830/118131334-eecd8700-b3ed-11eb-9665-c1fe084c87fe.jpg)
     The error is :Failed to open PTY,I search the error in the internet,I find it maybe caused by the /dev/pts not mount,but the script have the line :proot_command+=" -b /dev",so I think this error is caused by  inadequate permissions.it maybe also caused your's Mount mode。
      the speed start winetricks gui is quickly,this is good.
![Screenshot_2021-05-13-20-52-48-017_com realvnc viewer android](https://user-images.githubusercontent.com/57759830/118131524-276d6080-b3ee-11eb-8c8f-8d821f827e52.jpg)

**Comment by ZhymabekRoman** [comment]
Hello, I apologize that I did not answer, I was very busy. Thank you so much for the bug report, I will definitely see what is wrong there.

**Comment by ZhymabekRoman** [comment]
@fengxue-jrql, I unfortunately can't reproduce the bug, can you please provide more information? What version of Android do you have? And the phone manufacturer?

**Comment by ZhymabekRoman** [comment]
@ZhymabekRoman

**Comment by fengxue-jrql** [comment]
The phone is made in china.The phone model is Hongmi note9,the Android system is MIUI 12.0.6,Android 10。Termux Exagear version 2.0 is natural，but version 2.1 can't open pty。

**Comment by ZhymabekRoman** [comment]
https://user-images.githubusercontent.com/61125068/118452872-179f9600-b6e6-11eb-8df2-ba9d07664f8e.mp4

**Comment by fengxue-jrql** [comment]
I use the rootfs From you,and Execute the order git submodule init，git submodule update，and install xfce4 with apt update,apt install xfce4 tigervnc* ,on the first time,I edit the /root/.vnc/xstartup with you show in video,but it also can't open tty,on the second time，I rm -rf ~/.vnc/*,and start vnc with vnc.sh 
The content of vnc.sh is:
vncserver -kill :1
rm -rf /tmp/.X11-unix/X1
rm -rf /tmp/.X1-lock
vncserver :1 -depth 32
I think the error not caused by /root/.vnc/xstartup。
root@localhost:~# cat /etc/issue
Debian GNU/Linux 10 \n \l

**Comment by fengxue-jrql** [comment]
Above tty Change to pty

**Comment by fengxue-jrql** [comment]
root@localhost:~# cd /dev
bash: cd: /dev: Permission denied

**Comment by ZhymabekRoman** [comment]
Unfortunately I have this problem is not reproduced on my device, accordingly, I can not help you, maybe someone else can fix it
```
root@localhost:/# cd /dev
root@localhost:/dev# ls
...
```

**Comment by Abdalnablse10** [comment]
> Unfortunately I have this problem is not reproduced on my device, accordingly, I can not help you, maybe someone else can fix it
> 
> ```
> root@localhost:/# cd /dev
> root@localhost:/dev# ls
> ...
> ```

Correct me if I'm wrong but one reason why you are not getting the same problem is that you might have built exagear from source code on your phone on termux and that might have made it to only work perfectly on your phone's username so my bet if you build the source code on a deferent device you won't get the Failed to open PTY problem and there are two ways to fix this the first is to public the modified source code and give document how to build it or find a way to make it work on any user id/username

**Comment by ZhymabekRoman** [comment]
> one reason why you are not getting the same problem is that you might have built exagear from source code on your phone on termux

lmao, Exagear is closed-source, that is, proprietary, So it is unlikely to be the problem. The problem appeared after the commit https://github.com/ZhymabekRoman/Exagear-For-Termux/commit/44c1f3342e17940bd85f381020fb80b579d02843 and only two files were changed in that commit - bin/vpaths-list and start-exagear.sh

**Comment by ZhymabekRoman** [comment]
I have implemented a workaround that solves this problem. To do this, you need to run start-exagear with the parameter --old:
`start-exagear.sh login --old`
