### ISSUE TITLE
Bin folder not found problem

### ISSUE THREAD

**Issue by anwarmax-cpu** [ZhymabekRoman/Exagear-For-Termux#7]
Firstly  thank  you for your great effort and work my problem is as followes
```
ExaGear for Termux by Zhymabek_Roman
Version: 2.1
Copyright (c) 2013-2019 'Elbrus Technologies' LLC. All rights reserved.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


Folder 'bin' in guest system not found. The guest system is likely damaged
```
My problem is im using userland  apk program in adaptive storage since my phone storage  is very  very low in my opinion  i think the bin folder is located else were  if you can modify  the script  to  include  adaptive  storage aswel sorry  for the english  please help me

**Comment by anwarmax-cpu** [comment]
Sorry  for the second  comment  but i have to add my phone model 

Samsung  j2 prime 
Sm-g532f 
1.5gb ram 
8 gb storage  3gb usable !!! yes i 
128gb sdcard (adaptive  storage) bin storage  location unknown 
Userland v 2.7.3

**Comment by ZhymabekRoman** [comment]
Sorry for taking so long to answer, please tell me, did you run all the commands described in the README? And could you please provide me a screenshot of the below described commands?
```

**Comment by anwarmax-cpu** [comment]
Thanks you for your replay  
![S](https://user-images.githubusercontent.com/77493923/125167879-2fe5db80-e192-11eb-912b-8fc109bbfdcd.png)

**Comment by anwarmax-cpu** [comment]
userland is installed on the sdcard

**Comment by phoenix183** [comment]
I deployed Debian easily but getting the same error when trying for Alpine. @anwarmax-cpu can you list what filesystem structure your Debian tarfile  has?

**Comment by ZhymabekRoman** [comment]
I have implemented support for proot-based containers, i.e. AndroNix, Anlinux, UserLand in version 2.3
