### ISSUE TITLE
--shared-tmp

### ISSUE THREAD

**Issue by akbarri** [ZhymabekRoman/Exagear-For-Termux#8]
Is there any possibility to add this --shared-tmp command line?

**Comment by ZhymabekRoman** [comment]
> Is there any possibility to add this --shared-tmp command line?

same as in proot-distro?

**Comment by akbarri** [comment]
> > Is there any possibility to add this --shared-tmp command line?
> 
> same as in proot-distro?

Yes.
I tried modified start-exagear.sh within proot-distro methods but unsuccessful.

**Comment by ZhymabekRoman** [comment]
I'm sorry that I didn't answer for so long. I have already implemented the functionality, in the next version this functionality will be available. Syntax:
`./start-exagear login --shared-tmp`

**Comment by ZhymabekRoman** [comment]
Available in version 2.2
