### ISSUE TITLE
Can i swap  debian root fs to ubuntu root fs?

### ISSUE THREAD

**Issue by Dawimpy** [ZhymabekRoman/Exagear-For-Termux#9]
this is just a simple question.

Can i swap the debian rootfs to ubuntu rootfs?

cause i more like ubuntu :)

if can , please teach me how to do it. :)

**Comment by ZhymabekRoman** [comment]
Yes of course, just extract Ubuntu rootfs to exagear-fs folder. In the next few days I will add an Ubuntu roootfs image to the repository

**Comment by nagasawa** [comment]
please support proot-distro + termux-X11 version

**Comment by nagasawa** [comment]
$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu

**Comment by ZhymabekRoman** [comment]
> please support proot-distro

Exactly what do you want? Do you want Exagear for Termux to run in proot-distro? Or the ability to run proot-distro distributions in Exagear For Termux?

**Comment by nagasawa** [comment]
the ability to run proot-distro distributions in Exagear For Termux

**Comment by nagasawa** [comment]
```diff
diff --git a/start-exagear.sh b/start-exagear.sh
index 7762537..6d7924d 100755
--- a/start-exagear.sh
+++ b/start-exagear.sh
@@ -9,7 +9,7 @@
 PROGRAM_NAME="ExaGear for Termux"
 PROGRAM_VERSION="2.4"
 CURRENT_WORK_FOLDER=$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
-DEFAULT_ROOTFS_FOLDER="exagear-fs/"
+DEFAULT_ROOTFS_FOLDER="$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu"

 # Colors
 GREEN='\033[0;32m
```

**Comment by nagasawa** [comment]
```
[Starting x86 environment]

proot warning: can't sanitize binding "/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/sys/fs/selinux/": No such file or directory
lkv_SubstitutedPathsListEntry::create: substitution of the directory '/dev' is requested,
but in the guest image there is no directory named '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/dev'.
```

**Comment by ZhymabekRoman** [comment]
@nagasawa Lol, do you really think that this way you can run x86 distribution on arm system? By default, proot-distro downloads the arm version of distributions (if host system arch is arm), we need to have x86, so the above proposed method will not suit us, and even more so the proposed method does not allow you to run your custom distributions from the exagear-fs folder

**Comment by ZhymabekRoman** [comment]
@nagasawa Try to download proot-distro's distribution archives and exctract it to exagear-fs folder

**Comment by nagasawa** [comment]
Do you mean running wine on x86 linux?

**Comment by nagasawa** [comment]
I want to run windows.

**Comment by ZhymabekRoman** [comment]
> Do you mean running wine on x86 linux?

Yes

> I want to run windows.

No way. Only UNIX like OS only you can run on Android with minimal overhead. If you want run Windows application use Wine (fast), or emulate Windows in QEMU (veryyyyyy slowwww)

**Comment by nagasawa** [comment]
If I want to run windows applications, does that mean that arm64 wine is sufficient?

**Comment by ZhymabekRoman** [comment]
@nagasawa No, you need to user x86 Wine, because ARM version of Wine emulates Windows RT - in nutshell, this is a specialized version of Windows for arm, that can not to run a regular Windows application.

**Comment by nagasawa** [comment]
There seems to be a project that has made it possible to move it.
https://github.com/AndreRH/hangover

**Comment by nagasawa** [comment]
@nagasawa
It was a simple app, but it looked like a test project that didn't work.

**Comment by nagasawa** [comment]
It would be helpful to be able to pass proot options. I want to use --bind.

**Comment by nagasawa** [comment]
/sdcard & $HOME
I want to bind.

**Comment by nagasawa** [comment]
I'd like to see support for more than just bash.

**Comment by nagasawa** [comment]
```
grep "root" exagear-fs/etc/passwd | rev | cut -d ':' -f 1 | rev

/bin/zsh
```

**Comment by nagasawa** [comment]
```bash
    passwd=`grep "root" $DIST_PATH/etc/passwd`
    shell=${passwd##*:}
    shell_name=${shell##*/}
```

**Comment by nagasawa** [comment]
Is amd64 supported?

**Comment by ZhymabekRoman** [comment]
> Is amd64 supported ?

I tried to add amd64 support using the latest Exagear from Huawei, but seems no way

**Comment by ZhymabekRoman** [comment]
> There seems to be a project that has made it possible to move it.
> https://github.com/AndreRH/hangover

It is very slow, because it uses QEMU to emulate the x86 architecture

**Comment by ZhymabekRoman** [comment]
> It would be helpful to be able to pass proot options. I want to use --bind.

> I'd like to see support for more than just bash.

Well, I'll think about these functions as soon as I find the time. By the way PR is welcome
